# TO DO
# -CRUD BUS LIST (SPATIAL REFERENCE)
# -CRUD BUS DRIVER LIST (SPATIAL REFERENCE)
# -CRUD BUS DRIVERS BY BUS LINE
# -CRUD PASSENGER LIST (SPATIAL REFERENCE)
# -CRUD PASSENGER LIST BY BUS LINE
# MAP GENERATION:
# - BUSES
# - BUS DRIVERS
# - PASSENGERS